PROGRAM MAIN
IMPLICIT NONE
INTEGER::N,K,I,POS,REMAINS,J,P,DPOS
INTEGER,DIMENSION(:),ALLOCATABLE::CIRCLE, TEMP
INTEGER,DIMENSION(:),ALLOCATABLE::PERMITATION
READ*,N,K
ALLOCATE(CIRCLE(N))
CIRCLE=[(I, I=1,N)]
REMAINS=N
POS=0
P=1
DPOS=0

ALLOCATE(PERMITATION(N))

DO WHILE(REMAINS>0)
    IF (K/=REMAINS) THEN
      POS=POS+MOD(K,REMAINS)
      DO WHILE(POS>REMAINS)
      POS=POS-REMAINS
      END DO
    ELSE IF(K==REMAINS)THEN
      IF(POS==0)THEN
        POS=K
      ELSE
      
      END IF
    END IF
    PERMITATION(P)=CIRCLE(POS)
    P=P+1
    
    ALLOCATE(TEMP(REMAINS-1))
    J=1
    DO I=1,REMAINS
    IF (CIRCLE(I)==CIRCLE(POS)) THEN
    ELSE
        TEMP(J)=CIRCLE(I)
        J=J+1
    END IF
    END DO

    DEALLOCATE(CIRCLE)
    ALLOCATE(CIRCLE(REMAINS-1))
    CIRCLE=TEMP(1:REMAINS-1)
    DEALLOCATE(TEMP)
    REMAINS=REMAINS-1
    IF (POS-1==0) THEN
      POS=REMAINS
    ELSE
      POS=POS-1
    END IF
END DO


WRITE(*,'(A)',ADVANCE='NO') '<'
WRITE(*,'(I0)',ADVANCE='NO') PERMITATION(1)
DO I=2,N
WRITE(*,'(A2,I0)',ADVANCE='NO') ", " ,PERMITATION(I)
END DO
WRITE(*,'(A)',ADVANCE='NO') '>'
END PROGRAM
