
!NOT FINISHED // 미완성
!DOUBLE FREE ERROR EXISTS

PROGRAM MAIN
IMPLICIT NONE
INTEGER::N,K,DELETE,REMAIN,I,J,R,L !N,K 빼고 나머지 반복변수
INTEGER,DIMENSION(:),ALLOCATABLE::CIRCLE, TEMP
INTEGER,DIMENSION(:),ALLOCATABLE::PERMITATION
READ*,N,K
ALLOCATE(CIRCLE(N))
CIRCLE=[(I, I=1,N)]
ALLOCATE(PERMITATION(N))
REMAIN=N
L=1
R=1

DO WHILE(REMAIN/=0)
    DO WHILE(K>REMAIN)
    K=MOD(K,REMAIN)
    END DO
    
    PERMITATION(L)=CIRCLE(K)
    L=L+1
    REMAIN=REMAIN-1
    
    ALLOCATE(TEMP(REMAIN))
    DO J=1,REMAIN+1
        IF (CIRCLE(J)==CIRCLE(K)) THEN
        
        ELSE
            TEMP(R)=CIRCLE(J)
            R=R+1
        END IF
    END DO
    
    DEALLOCATE(CIRCLE)
    ALLOCATE(CIRCLE(REMAIN))
    DO J=1,REMAIN
    CIRCLE(J)=TEMP(J)
    END DO
    DEALLOCATE(TEMP)
END DO

WRITE(*,'(A)',ADVANCE='NO') '<'
WRITE(*,'(I0)',ADVANCE='NO') PERMITATION(1)
DO I=2,N
WRITE(*,'(A2,I0)',ADVANCE='NO') ", " ,PERMITATION(I)
END DO
WRITE(*,'(A)',ADVANCE='NO') '>'
END PROGRAM
